version: '3.8'
services:
  hashid-dev:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    container_name: hashid-dev
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
