version: '3.8'
services:
  hashID-dev:
    image: mcr.microsoft.com/devcontainers/go:1-1.21-bookworm
    container_name: hashID-dev
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
